# Generated by Django 3.2.15 on 2022-10-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, unique=True, verbose_name='Марка машины')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Модель машины')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carbrand', verbose_name='Марка машины')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, unique=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество заданных машин')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carmodel', verbose_name='Модель машины в заказе')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.color', verbose_name='Цвет машины в заказе')),
            ],
        ),
    ]
