# Generated by Django 3.2.15 on 2022-10-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_car_name'),
        ),
    ]
